export const PatientData = [
    {
        id: 1,
        patientIdNo: 'BSF-2023-002',
        firstName: 'CARMELA',
        lastName: 'DAGUPAN',
        middleInitial: 'CRUZ',
        email: 'carmellaDagupan@gmail.com',
        civilStatus: 'Single',
        sex: 'F',
        age: '34',
        bloodType: 'O+',
        birthdate: '08/25/2024',
        householdMonthlyIncome: '15,000',
        NoLivingChild: '1',
        NoNoneLivingChild: '0',
        support: '4PS',
        birthPlace: 'Gatas Pagadian city',
        purok: 'Bonifacio St.',
        barangay: 'GATAS DISTRICT',
        municipality: 'Pagadian city',
        province: 'Zamboanga del sur',
        Nationality: 'FILIPINO',
        religion: 'catholic',
        contactUs: '09509820178',
        dateRegistered: '08/08/2024',
        occupation: 'house wife',
        emergencyContactPerson: [
            {
                lastName: 'SOTOMAYOR',
                firstName: 'KYRVIN',
                middleInitial: 'SANGRENES',
                relationship: 'spouse',
                civilStatus: 'Married',
                address: 'San francisco',
                birthdate: '15/06/1998',
                age: '40',
                occupation: 'programmer',
                nationality: 'FILIPINO',
                religion: 'catholic',
                contactNo: '09976546878',
            }
        ]
    },
    {
        id: 2,
        patientIdNo: 'BSF-2023-003',
        firstName: 'MARIA',
        lastName: 'REYES',
        middleInitial: 'LOPEZ',
        email: 'mariaReyes@gmail.com',
        civilStatus: 'Married',
        sex: 'F',
        age: '28',
        bloodType: 'A+',
        birthdate: '12/10/1995',
        householdMonthlyIncome: '20,000',
        NoLivingChild: '2',
        NoNoneLivingChild: '0',
        support: 'INDIGENT',
        birthPlace: 'Pagadian city',
        purok: 'Poblacion',
        barangay: 'Poblacion',
        municipality: 'Pagadian city',
        province: 'Zamboanga del sur',
        Nationality: 'FILIPINO',
        religion: 'catholic',
        contactUs: '09123456789',
        dateRegistered: '09/15/2024',
        occupation: 'teacher',
        emergencyContactPerson: [
            {
                lastName: 'REYES',
                firstName: 'JUAN',
                middleInitial: 'PEREZ',
                relationship: 'husband',
                civilStatus: 'Married',
                address: 'Poblacion',
                birthdate: '03/02/1990',
                age: '34',
                occupation: 'engineer',
                nationality: 'FILIPINO',
                religion: 'catholic',
                contactNo: '09876543210',
            }
        ]
    },
    {
        id: 3,
        patientIdNo: 'BSF-2023-004',
        firstName: 'JOHN',
        lastName: 'DOE',
        middleInitial: 'SMITH',
        email: 'johnDoe@gmail.com',
        civilStatus: 'Single',
        sex: 'M',
        age: '45',
        bloodType: 'B-',
        birthdate: '06/30/1979',
        householdMonthlyIncome: '30,000',
        NoLivingChild: '0',
        NoNoneLivingChild: '1',
        support: 'PRIVATE',
        birthPlace: 'Pagadian city',
        purok: 'Del Pilar',
        barangay: 'Del Pilar',
        municipality: 'Pagadian city',
        province: 'Zamboanga del sur',
        Nationality: 'FILIPINO',
        religion: 'catholic',
        contactUs: '09223334455',
        dateRegistered: '10/01/2024',
        occupation: 'manager',
        emergencyContactPerson: [
            {
                lastName: 'DOE',
                firstName: 'JANE',
                middleInitial: 'ANN',
                relationship: 'sister',
                civilStatus: 'Single',
                address: 'Del Pilar',
                birthdate: '11/11/1985',
                age: '38',
                occupation: 'nurse',
                nationality: 'FILIPINO',
                religion: 'catholic',
                contactNo: '09112223344',
            }
        ]
    },
    {
        id: 4,
        patientIdNo: 'BSF-2023-005',
        firstName: 'ANNA',
        lastName: 'CRUZ',
        middleInitial: 'LOPEZ',
        email: 'annaCruz@gmail.com',
        civilStatus: 'Married',
        sex: 'F',
        age: '29',
        bloodType: 'AB+',
        birthdate: '04/20/1995',
        householdMonthlyIncome: '25,000',
        NoLivingChild: '3',
        NoNoneLivingChild: '0',
        support: '4PS',
        birthPlace: 'Gatas Pagadian city',
        purok: 'San Jose',
        barangay: 'San Jose',
        municipality: 'Pagadian city',
        province: 'Zamboanga del sur',
        Nationality: 'FILIPINO',
        religion: 'catholic',
        contactUs: '09334445566',
        dateRegistered: '09/12/2024',
        occupation: 'sales agent',
        emergencyContactPerson: [
            {
                lastName: 'CRUZ',
                firstName: 'MARK',
                middleInitial: 'JOHN',
                relationship: 'husband',
                civilStatus: 'Married',
                address: 'San Jose',
                birthdate: '01/25/1990',
                age: '34',
                occupation: 'businessman',
                nationality: 'FILIPINO',
                religion: 'catholic',
                contactNo: '09112233445',
            }
        ]
    },
];
